name: Manual PyInstaller Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] #, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Python version from .python-version
        run: echo "PY=$(cat meta/.python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY }}

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r meta/requirements-build.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon="src/assets/logos/window_logo.ico" "app.py"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gui-app-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloads

      - name: Read app version
        run: echo "VERSION=$(cat meta/VERSION)" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "Nemesis-XT - Text Editor v${{ env.VERSION }}"
          body_path: .github/README.md
          files: downloads/**/*  # upload all platform binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
